[package]
name = "substrate-stellar-xdr"
version = "0.1.0"
authors = ["Torsten Stüber <torsten@satoshipay.io>"]
edition = "2018"

[dependencies]
sp-std = { default-features = false, version = "3.0.0" }

[features]
default = ["main-types-only"]
main-types-only = []